spring:
# datasource configuration
  datasource:
    username: sa
    password: prod
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
# H2 console configuration
  h2:
    console.enabled: true
    console:
      path: /h2-console
